---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
    named_run_list: debian
  - name: ubuntu-14.04
    named_run_list: debian
  - name: ubuntu-12.04
    named_run_list: debian
  - name: centos-7.2
    named_run_list: centos
  - name: centos-6.8
    named_run_list: centos
  - name: centos-5.11
    named_run_list: centos

suites:
  - name: default
    provisioner:
      policyfile: test/fixtures/policies/default.rb
