---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.1
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[hashicorp-vault::default]
