name 'hashicorp-vault'
maintainer 'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license 'Apache-2.0'
description 'Application cookbook for installing and configuring Vault.'
long_description 'Application cookbook for installing and configuring Vault.'
issues_url 'https://github.com/sous-chefs/vault/issues'
source_url 'https://github.com/sous-chefs/vault'
chef_version '>= 12.5'
version '3.0.0'

supports 'ubuntu', '>= 14.04'
supports 'redhat', '>= 6.4'
supports 'centos', '>= 6.4'
supports 'windows'
supports 'freebsd'

depends 'build-essential', '>= 5.0'
depends 'golang', '~> 1.7'
depends 'poise', '~> 2.6'
depends 'poise-service', '~> 1.1'
depends 'poise-archive'

gem 'poise', '~> 2.8'
gem 'poise-service', '~> 1.5'
gem 'poise-boiler'
