name 'hashicorp-vault'
maintainer 'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license 'Apache-2.0'
description      'Installs and configures Rundeck 2.x'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
issues_url 'https://github.com/sous-chefs/vault/issues'
source_url 'https://github.com/sous-chefs/vault'
version '3.0.0'

supports 'ubuntu', '>= 14.04'
supports 'redhat', '>= 6.4'
supports 'centos', '>= 6.4'
supports 'windows'
supports 'freebsd'

depends 'build-essential', '>= 5.0'
depends 'golang', '~> 1.7'
depends 'poise', '~> 2.6'
depends 'poise-service', '~> 1.1'
depends 'poise-archive'
